### ISSUE TITLE
Dialog box to enter game location not working

### ISSUE THREAD

**Issue by posLop** [sekwah41/mobalytics-repackager#15]
Ik that the fonts are broken for the file explorer but when i hit cancel it does not give me a box to enter the location manually.  i remember that it used to and when i reinstalled it no longer does.  without this it is unusable.

**Comment by sekwah41** [comment]
Ill check once im done with work in about an hour :)

The patch may have changed location and not be triggering properly. It tries to apply the patches to the latest versions but doesn't always get it perfect.

**Comment by sekwah41** [comment]
I will upload a fix later, just fixed up some of the patches :)

**Comment by posLop** [comment]
thank you so much.  was a little buggy but after restart worked perfectly.
