### ISSUE TITLE
Mobalytics moving to Overwolf, might be worth trying with Blitz

### ISSUE THREAD

**Issue by emaxoda** [sekwah41/mobalytics-repackager#29]
Since Mobalytics has moved to Overwolf the defaut technique you were using no longer works. 
I tried unpacking Blitz, repackaged it and it opens, the only things to do left are solving some problems with game location. 
For example Blitz won't let you pick the game folder as it tries to autodetect the game via a .lnk or the json file with the location on C:\\Riot Games\

**Comment by emaxoda** [comment]
![image](https://user-images.githubusercontent.com/16837067/203823994-d6bad060-60c9-4c7c-8bc2-c46b10ec814e.png)

**Comment by sekwah41** [comment]
Will have to, Im not sure how long the API's and things mobalytics uses will work with the old app but some way forwards may be good.

If it wasn't for the fact I don't have enough time right now I would probably do that in the next few weeks or look at writing my own cross-platform alternative if any of the platforms have public API's

**Comment by sekwah41** [comment]
Might be a good project to also look into for the holidays to make an alternative depending on how much time I have but as I am struggling with internet quality lately ive not been playing as much league but I do love to play with numbers and things.

**Comment by sekwah41** [comment]
Might be a good project to also look into for the holidays to make an alternative depending on how much time I have but as I am struggling with internet quality lately ive not been playing as much league but I do love to play with numbers and things.

**Comment by emaxoda** [comment]
okay i tested the lastest non-overwolf version and the api is still working. But it requieres a few changes, they introduced a module of their own, called moba-shared so we can't delete the node_modules folder like before but that's not an issue since we can skip that and it still works. 
![image](https://user-images.githubusercontent.com/16837067/206052436-daf91640-c356-4e69-8963-61a2537f72a6.png)
![image](https://user-images.githubusercontent.com/16837067/206052461-8f9dbb8d-d7c1-48d9-b367-cb4c4480c406.png)

**Comment by emaxoda** [comment]
ah, i forgot, they are using electron 19 so that's a lot better for wayland compatibilty
that's the other change i made. I'll do a proper push request later

**Comment by sekwah41** [comment]
Ooh nice :D ive been slowly trying to ramp up how much I work on my projects again as life just got a bit busy :P Its nice to know things are getting better wayland compatability. I havent touched wayland too much tbh.

**Comment by sekwah41** [comment]
Taking a look, it looks like the same extraction method or at least a similar one may work to re-package blitz.

I will try to explore later this week creating a blitz version for this too :) as well as I may have another go at getting their overlays working as I got pretty far last time (though it'll probably be laggy as hell)

**Comment by sekwah41** [comment]
Closing to keep track over here https://github.com/sekwah41/blitz-repackager/issues/1

Accidentally ran rm -rf too high in the project and deleted all my progress :( Though seemed promising so far.

Will try to remake from scratch and clean up some of the scripts as to not leave bloat from mobalytics.

**Comment by sekwah41** [comment]
Sadly blitz do too much of their code in pre-compiled node files. Its not worth the effort sadly :(

**Comment by emaxoda** [comment]
Yeah sorry for the late response but I got to the same end, too many precompiled node files
